#!/usr/bin/env bash
# Configure a load balancer
sudo hostnamectl set-hostname "$(sed -n '/127.0.0.1/p' /etc/hosts | cut -d' ' -f3)"

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy=1.8.\*
CONFIG="
frontend http
  bind *:80
  mode http
  default_backend web-backend

backend web-backend
  balance roundrobin
  server 541-web-01 35.196.185.161:80 check
  server 541-web-02 104.196.150.129:80 check
"
echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
